
name: Container Build

on:
  push:
    paths:
      - 'context/**'
      - '.github/workflows/ci.yml'
    branches:
      - '**'
    tags:
      - '*.*.*'

env:
  DOCKER_REPO: tomeichlersmith/hps-env

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    -
      name: Setup QEMU
      uses: docker/setup-qemu-action@v2
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - 
      name: Cache Docker Layers on GitHub
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-${{ hashFiles('context/**') }}
        restore-keys: |
          ${{ runner.os }}-${{ hashFiles('context/**') }}
          ${{ runner.os }}
    -
      name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - 
      name: Get Build Context
      uses: actions/checkout@v3
    -
      name: Determine Image Tags
      id: generate_tag
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.DOCKER_REPO }}
    -
      name: Build the Image
      uses: docker/build-push-action@v3
      with:
        context: context
        file: context/Dockerfile
        push: true 
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache
        tags: ${{ steps.generate_tag.outputs.tags }}
        labels: ${{ steps.generate_tag.outputs.labels }}
